---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SQS FIFO Test

Parameters:
  Name:
    Type: String
    Default: sqs-test

Globals:
  Function:
    Runtime: python3.8

Resources:

  DynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Name}-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

