---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SQS FIFO Test

Parameters:
  Name:
    Type: String
    Default: sqs-test

Globals:
  Function:
    Runtime: python3.8

Resources:

  DynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Name}-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

  WriteToDDBLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Name}-handler
      Environment:
        Variables:
          table: !Ref DynamoDB
      CodeUri: src
      Handler: handler.lambda_handler
      Events:
        FIFOQueue:
          Type: SQS
          Properties:
            Enabled: true
            Queue: !GetAtt FIFOQueue.Arn
        StdQueue:
          Type: SQS
          Properties:
            Enabled: true
            Queue: !GetAtt StdQueue.Arn
      Description: write records to DynamoDB table
      Policies:
        - Statement:
          - Sid: DynamoDBPartiQLWritePolicy
            Effect: Allow
            Action: dynamodb:PartiQLInsert
            Resource: !Sub arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDB}
        - SQSPollerPolicy:
            QueueName: !GetAtt StdQueue.QueueName
        - SQSPollerPolicy:
            QueueName: !GetAtt FIFOQueue.QueueName

  SendMessagesToFIFOQueueLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Name}-send-messages-to-fifo-queue
      Environment:
        Variables:
          fifo_queue: !Ref FIFOQueue
      CodeUri: src
      Handler: send_messages.send_to_fifo_queue
      Description: Send messages to SQS FIFO queue
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt FIFOQueue.QueueName

  SendMessagesToStdQueueLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Name}-send-messages-to-std-queue
      Environment:
        Variables:
          std_queue: !Ref StdQueue
      CodeUri: src
      Handler: send_messages.send_to_std_queue
      Description: Send messages to SQS standard queue
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt StdQueue.QueueName

  StdQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${Name}-sqs-std-queue

  FIFOQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: true
      QueueName: !Sub ${Name}-sqs-fifo-queue.fifo
